pipeline {
  agent {
    docker {
      image 'bharadwaja27/custom-maven-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
  }
  stages {
    stage('Checkout') {
      steps {
        sh 'echo passed'
        //git branch: 'main', url: 'https://github.com/bharadwaja2711/Jenkins.git'
      }
    }
    stage('Build and Test') {
      steps {
        sh 'apt-get update && apt-get install -y openjdk-17-jdk' // Install Java 17
        sh 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 && cd ULTIMATE-CICD-PIPELINE/spring-boot-app && mvn clean package'
      }
    }
    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "bharadwaja27/ultimate-cicd:${BUILD_NUMBER}"
        // DOCKERFILE_LOCATION = "ULTIMATE-CICD-PIPELINE/spring-boot-app/Dockerfile"
        REGISTRY_CREDENTIALS = credentials('docker-cred')
      }
      steps {
        script {
            sh 'cd ULTIMATE-CICD-PIPELINE/spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
            def dockerImage = docker.image("${DOCKER_IMAGE}")
            docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                dockerImage.push()
            }
        }
      }
    }
    stage('Update Deployment File') {
        environment {
            GIT_REPO_NAME = "Jenkins"
            GIT_USER_NAME = "bharadwaja2711"
        }
        steps {
            withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                sh '''
                    git config user.email "bharadwaja1.618@gmail.com"
                    git config user.name "Manoj Bharadwaja"
                    BUILD_NUMBER=${BUILD_NUMBER}
                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" ULTIMATE-CICD-PIPELINE/spring-boot-app-manifests/deployment.yml
                    git add ULTIMATE-CICD-PIPELINE/spring-boot-app-manifests/deployment.yml
                    git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                '''
            }
        }
    }
  }
}

